version: "3.6"
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    networks:
      - onlyoffice
    container_name: postgres
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=redmine
  redmine:
    container_name: app-server
    image: redmine:${SERVICE_TAG}
    restart: unless-stopped
    networks:
      - onlyoffice
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - REDMINE_DB_POSTGRES=postgres
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=redmine
    volumes:
      - /connector:/usr/src/redmine/plugins
networks:
  default:
    name: onlyoffice