version: '3'
services:
  app:
    container_name: app-server
    image: "alste/php8.1-nocode:latest"
    restart: always
    ports:
      - 8080:8080
    networks:
      - onlyoffice
    environment:
      SQL_DB_TYPE: mariadb
      SQL_DB_HOST: mariadb
      SQL_DB_NAME: ${SQL_DB_NAME}
      SQL_DB_USER: ${SQL_DB_USER}
      SQL_DB_PASS: ${SQL_DB_PASS}
      HTTP_PROTO: ${HTTP_PROTO}
      HTTP_URL: ${DOMAIN_NAME}
    volumes:
      - /app/moodle/moodle_git:/var/www/html/appserver
#      - moodledata_data:/bitnami/moodledata
#      - /app/moodle/run.sh:/run.sh
#      - ./onlyoffice:/tmp/onlyoffice
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    image: mariadb:10.6.7
    restart: always
    networks:
      - onlyoffice
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ${SQL_DB_NAME}
      MYSQL_USER: ${SQL_DB_USER}
      MYSQL_PASSWORD: ${SQL_DB_PASS}
#    volumes:
#      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  onlyoffice:
    driver: 'bridge'
#volumes:
#  mariadb_data:
#  moodle_data:
#  moodledata_data:
