version: '3'
services:
  app:
    container_name: app-server
    image: "moodlehq/moodleapp:${SERVICE_TAG}"
    restart: always
    expose:
      - 8080:80
    networks:
      - onlyoffice
#    environment:
#      - MOODLE_DATABASE_HOST=mariadb
#      - MOODLE_DATABASE_PORT_NUMBER=3306
#      - MOODLE_DATABASE_USER=bn_moodle
#      - MOODLE_DATABASE_NAME=bitnami_moodle
##      # ALLOW_EMPTY_PASSWORD is recommended only for development.
#      - ALLOW_EMPTY_PASSWORD=yes
#      - MOODLE_USERNAME=${MOODLE_ADMIN_LOGIN}
#      - MOODLE_PASSWORD=${MOODLE_ADMIN_PASSWORD}
#      - MOODLE_EMAIL=${EMAIL_NAME}
#      - MOODLE_SITE_NAME='New Test Site'
#    volumes:
#      - moodle_data:/bitnami/moodle
#      - moodledata_data:/bitnami/moodledata
#      - /app/moodle/run.sh:/run.sh
#      - ./onlyoffice:/tmp/onlyoffice
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/assets/env.json || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
#    command: bash /run.sh
  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:10.3
    restart: always
    networks:
      - onlyoffice
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
#    volumes:
#      - mariadb_data:/bitnami/mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  onlyoffice:
    driver: 'bridge'
#volumes:
#  mariadb_data:
#  moodle_data:
#  moodledata_data:
