version: '3'
services:
  app:
    container_name: app-server
#    image: "moodlehq/moodleapp:${SERVICE_TAG}"
    image: "alste/moodle:latest"
    restart: always
    ports:
      - 8080:8080
    networks:
      - onlyoffice
    environment:
      - SQL_DB_TYPE=mariadb
      - SQL_DB_HOST=mariadb
      - SQL_DB_NAME=moodledb
      - SQL_DB_USER=moodle
      - SQL_DB_PASS=moodle
      - HTTP_PROTO=http
      - HTTP_URL=alt.office24.site
#    volumes:
#      - moodle_data:/bitnami/moodle
#      - moodledata_data:/bitnami/moodledata
#      - /app/moodle/run.sh:/run.sh
#      - ./onlyoffice:/tmp/onlyoffice
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    image: mariadb:10.6.7
    restart: always
    networks:
      - onlyoffice
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: moodledb
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
#    volumes:
#      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  onlyoffice:
    driver: 'bridge'
#volumes:
#  mariadb_data:
#  moodle_data:
#  moodledata_data:
